repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    createNamespace: true
    values:
      - values/traefik.yaml
      
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.14.0
    createNamespace: true
    values:
      - values/cert-manager.yaml
      - values/pvc.yaml

  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    values:
      - values/metrics.yaml
