# Main helmfile - references all service helmfiles
helmDefaults:
  atomic: false
  wait: true
  timeout: 10m

helmfiles:
  - path: traefik/helmfile.yaml

  - path: cert-manager/helmfile.yaml

  - path: cert-manager-webhook-hetzner/helmfile.yaml

  - path: metrics-server/helmfile.yaml

  - path: tailscale/helmfile.yaml
