apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:1oIqhdYLVcMOMxsAnoVWSVAHDCNcKdfDXaxkSHOGzzTM7kSO1jfDyfwuTmnBhr4xugKWavVImgJQ+T0WgUv0dQ==,iv:WPL97qb4hfSg7qCbHzOvKzoaN1dVjcBRA+CB618knKY=,tag:a/uIhDSBWgJGAK2tpa8Z/Q==,type:str]
sops:
    age:
        - recipient: age104xl76udz4syr3x4ltju2rcdd0mkvran3jv4520lyewgy2r0lgss9xly5z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbW00dzRGWHlCNGpVSU04
            TlN5TXViZkNqSHg5blROTE04VGZUUHlDSUZ3CkdrSTk1UXJOUDYzU1BIbER1RTNJ
            djlEeW8ra2k0QTdsVE9SbTBmRGJyL0EKLS0tIEpvdzhLUlZka2p5UkNheThzcWxT
            TUdKZ3N3SW1GQnRKYzRJU21lMGRlZzAKv4U+UbjpYGtxn7l9TZ748H4ukFP6Caaj
            XpHjBdIffWqwHeTKstCnJGjiyfRv4XCekO0ZWubQnCCxhJvAtYipuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14jnakt2vsmd37czh5wgn7ghkr276papa0vx2algs2lwhu9t3ufzsav9mlk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudEhWRHFzL0pjZzM1aHhu
            Q3dEM3FrWUZ5L3lBMW9vaXg3UlZzQjczR2hJClRrQWswc2t1MG1pWFhhRWZjM1Iz
            K3VRN2I1dllha1dFY0dVYlUrOS8wY1kKLS0tIGJLeE1nSlZLSHNvZ1pkVTdlSmlp
            aVIvbkY0bFViMVBHSENIL2pzZjJydlEKmxFIv5Gb52cLQv4+Qs+LcUhSWq29+k+g
            bcfCcdJoQX+qUYIpYrGnNnGP2lPIfr9WgAv6m7aVwOBmPMqnVCaZOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T23:30:40Z"
    mac: ENC[AES256_GCM,data:2et8S0RVdX61sqwo5memMua0EYB73zVwFhjMDCHw/ueg21AVOoAIbqx6U1I4RWwX2NQ9I3n1l+txWfir0fTtCX+2hZfvxGJNJ8Vc/V1caPczuKO1e3IchF8hDYJuEYGrJ00xy0FDoiSCmApguJSKn8LmQpkr0G2RmdypOj9rr0k=,iv:qsVCX3amiT77v/cVLA0VyUnU9kVhTj5Ij3cnOKHQcGI=,tag:37jLg/XDcnnBOj3cJAVhqQ==,type:str]
    encrypted_regex: ^(data|oauth|stringData)$
    version: 3.12.2
