repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 39.0.2
    createNamespace: true
    values:
      - values.yaml
